# Generated by Django 3.1.2 on 2021-04-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_hobi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agama', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Agama',
            },
        ),
        migrations.CreateModel(
            name='Citacita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'CItacita',
            },
        ),
        migrations.CreateModel(
            name='Statusasalsantri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusasalsantri', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statusasalsantri',
            },
        ),
        migrations.CreateModel(
            name='Statushidupayah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statushidupayah', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statushidupayah',
            },
        ),
        migrations.CreateModel(
            name='Statushidupibu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statushidupibu', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statushidupibu',
            },
        ),
    ]
