# Generated by Django 3.2 on 2021-06-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_pendidikanayah_pendidikanibu_pendidikanwali_penghasilan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agama',
            name='agama',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='citacita',
            name='cita',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hobi',
            name='hobi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jeniskelamin',
            name='jenis',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikanayah',
            name='pendidikanayah',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikanibu',
            name='pendidikanibu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikanwali',
            name='pendidikanwali',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='penghasilan',
            name='penghasilan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statushidupayah',
            name='statushidupayah',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statushidupibu',
            name='statushidupibu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tahunpelajaran',
            name='tahun_pelajaran',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
