# Generated by Django 3.1.2 on 2021-07-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20210629_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendidikanayah',
            old_name='pendidikanayah',
            new_name='pendidikan_ayah',
        ),
        migrations.RenameField(
            model_name='pendidikanibu',
            old_name='pendidikanibu',
            new_name='pendidikan_ibu',
        ),
        migrations.RenameField(
            model_name='pendidikanwali',
            old_name='pendidikanwali',
            new_name='pendidikan_wali',
        ),
        migrations.RenameField(
            model_name='statusasalsantri',
            old_name='statusasalsantri',
            new_name='status_asal_santri',
        ),
        migrations.RenameField(
            model_name='statushidupayah',
            old_name='statushidupayah',
            new_name='status_hidup_ayah',
        ),
        migrations.RenameField(
            model_name='statushidupibu',
            old_name='statushidupibu',
            new_name='status_hidup_ibu',
        ),
    ]
