# Generated by Django 3.0.8 on 2020-12-10 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0002_auto_20201204_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=200, null=True)),
                ('nama', models.CharField(max_length=300, null=True)),
                ('propinsi', models.CharField(blank=True, max_length=150, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=150, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=150, null=True)),
                ('alamat', models.TextField(blank=True, max_length=500, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('namaayah', models.CharField(blank=True, max_length=300, null=True)),
                ('pekerjaanayah', models.CharField(blank=True, max_length=200, null=True)),
                ('nohpayah', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatanayah', models.CharField(blank=True, max_length=200, null=True)),
                ('alamatayah', models.TextField(blank=True, max_length=500, null=True)),
                ('namaibu', models.CharField(blank=True, max_length=300, null=True)),
                ('pekerjaanibu', models.CharField(blank=True, max_length=200, null=True)),
                ('nohpibu', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatanibu', models.CharField(blank=True, max_length=200, null=True)),
                ('alamatibu', models.TextField(blank=True, max_length=500, null=True)),
                ('namawali', models.CharField(blank=True, max_length=300, null=True)),
                ('pekerjaanwali', models.CharField(blank=True, max_length=200, null=True)),
                ('nohpwali', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatanwali', models.CharField(blank=True, max_length=200, null=True)),
                ('alamatwali', models.TextField(blank=True, max_length=500, null=True)),
                ('jeniskelamin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Jeniskelamin')),
                ('lemabaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Lembaga')),
                ('tahunpelajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Tahunpelajaran')),
                ('wilayah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Wilayah')),
            ],
            options={
                'verbose_name_plural': 'Santri',
            },
        ),
    ]
