# Generated by Django 3.0.8 on 2020-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='foto',
            field=models.ImageField(default='fotokosong.gif', upload_to='foto_pics'),
        ),
    ]
