# Generated by Django 3.0.8 on 2020-12-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0002_auto_20201209_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='santri',
            old_name='lemabaga',
            new_name='lembaga',
        ),
        migrations.AlterField(
            model_name='santri',
            name='foto',
            field=models.ImageField(blank=True, default='fotokosong.gif', upload_to='foto_pics'),
        ),
    ]
