# Generated by Django 3.0.8 on 2021-01-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0003_auto_20201212_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='alamat_sekolah_asal',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='anakke',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='citacita',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='hoby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='jumlahsaudara',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='nik',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='nisn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='noijasah',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='nokk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='sekolah_asal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='tanggallahir',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='tanggalmasukpesantren',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='tempatlahir',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
