# Generated by Django 3.0.8 on 2021-02-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0006_auto_20210203_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='santri',
            old_name='nam_aayah',
            new_name='nama_ayah',
        ),
        migrations.RenameField(
            model_name='santri',
            old_name='noh_payah',
            new_name='no_hp_ayah',
        ),
        migrations.AlterField(
            model_name='santri',
            name='nisn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
