# Generated by Django 3.1.7 on 2021-03-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0007_auto_20210203_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='cita_cita',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='hobi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='sekolah_asal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
