# Generated by Django 3.1.2 on 2021-03-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0009_auto_20210320_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='santri',
            old_name='no_ijasah',
            new_name='noi_jasah',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='diniyah',
        ),
    ]
