# Generated by Django 3.1.2 on 2021-03-28 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_wilayah_user'),
        ('appsantri', '0010_auto_20210327_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='diniyah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.diniyah'),
        ),
    ]
