# Generated by Django 3.1.2 on 2021-04-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0011_santri_diniyah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=200, null=True)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Catatan',
            },
        ),
    ]
