# Generated by Django 3.1.2 on 2021-04-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0012_catatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='nama',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='nik',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='nis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='no_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='noi_jasah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='tanggal_masuk_pesantren',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
