# Generated by Django 3.1.2 on 2021-04-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_agama_citacita_statusasalsantri_statushidupayah_statushidupibu'),
        ('appsantri', '0013_auto_20210416_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='hobi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.hobi'),
        ),
    ]
