# Generated by Django 3.1.2 on 2021-04-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_agama_citacita_statusasalsantri_statushidupayah_statushidupibu'),
        ('appsantri', '0014_auto_20210421_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santri',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='noi_jasah',
        ),
        migrations.AddField(
            model_name='santri',
            name='status_asal_santri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.statusasalsantri'),
        ),
        migrations.AddField(
            model_name='santri',
            name='status_hidup_ayah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.statushidupayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='status_hidup_ibu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.statushidupibu'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='cita_cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.citacita'),
        ),
    ]
