# Generated by Django 3.1.2 on 2021-04-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_agama_citacita_statusasalsantri_statushidupayah_statushidupibu'),
        ('appsantri', '0015_auto_20210421_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santri',
            name='alamat_ayah',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='alamat_ibu',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='email',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='no_kk',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='pendapatan_ayah',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='pendapatan_ibu',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='status_dalam_keluarga',
        ),
        migrations.AddField(
            model_name='santri',
            name='agama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.agama'),
        ),
    ]
