# Generated by Django 3.1.2 on 2021-04-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_pendidikanayah_pendidikanibu_pendidikanwali_penghasilan'),
        ('appsantri', '0016_auto_20210421_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santri',
            name='alamat_wali',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='pendapatan_wali',
        ),
        migrations.AddField(
            model_name='santri',
            name='pendidikan_ayah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.pendidikanayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pendidikan_ibu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.pendidikanibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pendidikan_wali',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.pendidikanwali'),
        ),
        migrations.AddField(
            model_name='santri',
            name='penghasilan_orang_tua_atau_wali_perbulan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.penghasilan'),
        ),
    ]
