# Generated by Django 3.2 on 2021-04-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_pendidikanayah_pendidikanibu_pendidikanwali_penghasilan'),
        ('appsantri', '0017_auto_20210421_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='santri',
            old_name='nis',
            new_name='nis_lembaga',
        ),
        migrations.AddField(
            model_name='santri',
            name='nis_pesantren',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='no_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='diniyah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.diniyah'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jenis_kelamin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.jeniskelamin'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='lembaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.lembaga'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='tahun_pelajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.tahunpelajaran'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='wilayah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.wilayah'),
        ),
    ]
