# Generated by Django 3.2 on 2021-04-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0018_auto_20210424_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santri',
            name='nis_lembaga',
        ),
    ]
