# Generated by Django 3.2 on 2021-04-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0019_remove_santri_nis_lembaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='nis_lembaga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
