# Generated by Django 3.1.2 on 2021-05-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0020_santri_nis_lembaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='santri_aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='catatan',
            name='keterangan',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
