# Generated by Django 3.2 on 2021-06-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0026_pesan_wilayah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesan',
            name='wilayah',
        ),
    ]
