# Generated by Django 3.2 on 2021-06-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0028_pesan_wilayah'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catatan',
        ),
    ]
