# Generated by Django 3.2 on 2021-06-25 14:30

import appsantri.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0029_delete_catatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=appsantri.models.PesanStatus),
        ),
    ]
