# Generated by Django 3.2 on 2021-06-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0030_pesan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='pesan_balasan',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
