# Generated by Django 3.2 on 2021-07-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0032_auto_20210629_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='keterangan_diniyah',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pesan',
            name='keterangan_lembaga',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pesan',
            name='keterangan_wilayah',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
