# Generated by Django 3.2 on 2021-07-02 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0034_auto_20210701_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesan',
            name='keterangan_diniyah',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='keterangan_lembaga',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='keterangan_wilayah',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='pesan_balasan_diniyah',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='pesan_balasan_lembaga',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='pesan_balasan_wilayah',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='status_diniyah',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='status_lembaga',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='status_wilayah',
        ),
    ]
