# Generated by Django 3.2 on 2021-07-03 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0035_auto_20210702_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
