# Generated by Django 3.2 on 2021-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsantri', '0037_santri_desa'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='nik_ayah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='nik_ibu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
